# Generated by Django 4.2.4 on 2023-09-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_tag_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
